Hello world in nodejs
szydan/gists pull request #4
Opened 2023-02-12 20:06 UTC by szydan

2023-02-13 11:05 UTC, emmaxdan requested changes

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +First program in any new language is called a hello world program.
The first program in any new language is called a hello world program.

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +Hello world program prints "Hello World" text on the screen.
make sure to put 'the' infront of hello world

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +Below an example in nodejs
Below is an example in nodejs

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +* you have a file called hellow-world.js
you have a file called hello-world.js

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +In ou first program we
In our first program we

2023-02-13 11:05 UTC, emmaxdan commented on nodejs/hello-world.md
> +* this object have few methods and we used one called `log`
this object has a few methods and we use one called `log`

2023-02-26 22:31 UTC, szydan commented
@emmaxdan corrected typos, next thing I would like to do it to run it together

2023-02-28 09:15 UTC, merged