Add character counter example
szydan/gists pull request #7
Opened 2023-03-18 14:29 UTC by szydan

2023-03-18 18:36 UTC, emmaxdan requested changes

2023-03-18 18:36 UTC, emmaxdan commented on .editorconfig
> +# which is always added by yarn and the IDE is always trying to remove it on save according to the above rule
```suggestion
# which is always added by yarn and the IDE is always trying to remove it on save according to the  rule above
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter-1.js
> +// print results in alphabetical order
```suggestion
// print the results in alphabetical order
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter-2.js
> +  // print results in alphabetical order
```suggestion
  // print the results in alphabetical order
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Let us write a bit more complex program.
```suggestion
Let us write a program that's a bit more complex 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +this letter occurred.
```suggestion
that letter occurred.
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +// print results in alphabetical order
```suggestion
// print the results in alphabetical order
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Here the results;
```suggestion
Here is the result;
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +The above program could be further improved
```suggestion
The program above could be further improved
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Here only a few things we could do:
```suggestion
Here are a few things we could do: 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +* print the letter statistics in better way, maybe as a graph
```suggestion
* print the letter statistics in a better way, for example, as a graph
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +All the above improvements would be nice, however our program has one issue which is more important to address.
```suggestion
The  improvements above would be nice, however our program has one issue which is more important to address. 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +The above line tell the computer to load the entire file into a variable text (memory).
```suggestion
It'll tell the computer to load the entire file into a variable text (memory).
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +When the file is small (few hundreds of characters) our program will use very little memory,
```suggestion
When the file is small (a few hundred characters) our program will use very little memory, 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +only a few hundreds of bytes.
```suggestion
only a few hundred bytes.
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +However if the file is huge it will use huge amount of memory.
```suggestion
However if the file is huge it will use a large amount of memory. 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +To fix this we will use another method of reading files - streams.
```suggestion
To fix this we will use another method of reading files called 'stream'
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Stream in computer programming refers to a data that is continuously flowing from source to destination.
```suggestion
Stream in computer programming refers to a data that is continuously flowing from the source to a destination. 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +This way our program will use only a small amount of memory at any given time regardless of how big the input file is.
```suggestion
This way our program will only use a small amount of memory at any given time regardless of how big the input file is.
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +  // print results in alphabetical order
```suggestion
  // print the results in alphabetical order
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +The second parameter (options) passed to createReadStream is telling how much memory
```suggestion
The second parameter (option) passed to createReadStream is telling how much memory 
```

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Now even if we tell it to read a 1 GB (giga byte) file it would use only 32 kb at any given time
you used the phrase 'at any given time' a lot of times, maybe say something different

2023-03-18 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Will notice that the version 1 is consuming much more memory.
```suggestion
You will notice that version 1 is consuming way more memory.
```

2023-03-19 17:13 UTC, szydan commented
@emmaxdan done all the fixes, please check again

2023-03-22 18:36 UTC, emmaxdan requested changes

2023-03-22 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Let us write a program that's a bit more complex.
```suggestion
Let's write a program that's a bit more complex. 
```

2023-03-22 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +next to each letter will be a number of how many times that letter occurred.
```suggestion
there  will be a number next to each letter of how many times that letter occurred.
```

2023-03-22 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Here is the result:
```suggestion
Here are the results:
```

2023-03-22 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +Stream in computer programming refers to a data that is continuously flowing from source to a destination.
```suggestion
Stream in computer programming refers to a data that is continuously flowing from a source to a destination. 
```

2023-03-22 18:36 UTC, emmaxdan commented on nodejs/character-counter/character-counter.md
> +You will notice that version 1 is consuming way more memory.
```suggestion
You'll notice that version 1 is consuming way more memory.
```

2023-04-08 13:09 UTC, merged